fix: Style clean up, editorconfig - Added editorconfig - Hard tab - Removed double spaces - Added new XDG_PROJECTS_DIR - Double quorte on scripts variables - local variables (bash) for status - scripts fixes

diff --git a/scripts/random-wallpaper b/scripts/random-wallpaper
--- a/scripts/random-wallpaper
+++ b/scripts/random-wallpaper
@@ -7,19 +7,19 @@ REMOTE_FILE_NAME="/tmp/$(date '+%s.jpg')"
 WALLPAPER=/tmp/current_wallpaper.jpg
 
 notify_and_exit () {
-    notify-send -i "$ICON_DIR/error.png" -u normal "Failed" "Unable to get Wallpapers from internet"
-    exit 1
+	notify-send -i "$ICON_DIR/error.png" -u normal "Failed" "Unable to get Wallpapers from internet"
+	exit 1
 }
 
 if [ "$1" = "--remote" ]; then
-    wget -q "$PIC_URL" -O "$REMOTE_FILE_NAME" || notify_and_exit
-    cp -f $REMOTE_FILE_NAME $WALLPAPER
+	wget -q "$PIC_URL" -O "$REMOTE_FILE_NAME" || notify_and_exit
+	cp -f $REMOTE_FILE_NAME $WALLPAPER
 else
-    WALLPAPER=$(find $WALLPAPER_DIR -type f | shuf -n1)
+	WALLPAPER=$(find $WALLPAPER_DIR -type f | shuf -n1)
 fi
 
 if pidof swaybg > /dev/null ; then
-    killall swaybg
+	killall swaybg
 fi
 
 swaybg -m fill -i $WALLPAPER
diff --git a/scripts/record-video b/scripts/record-video
--- a/scripts/record-video
+++ b/scripts/record-video
@@ -6,13 +6,13 @@ FILE=$(date +'%Y%e%d-%s.mp4')
 SHORT_FILE=$(date +'%s.mp4')
 
 if [ "$1" = "--kill" ]; then
-    killall wf-recorder
-    exit
+	killall wf-recorder
+	exit
 fi
 
 notify_and_exit () {
-    notify-send -i "$ICON_DIR/error.png" -u normal "Recording Failed" "Unable to record video"
-    exit 1
+	notify-send -i "$ICON_DIR/error.png" -u normal "Recording Failed" "Unable to record video"
+	exit 1
 }
 
 mkdir -p "$DIR"
@@ -25,8 +25,8 @@ NAME="$(wofi --dmenu -p "Enter name for video" -l 0)_$SHORT_FILE" || NAME="$FILE
 mv "$TEMP_FILE" "$DIR/$NAME" || notify_and_exit
 
 if [ -s "$DIR/$NAME" ]; then
-    notify-send -i "$ICON_DIR/video.png" -u normal "Video Saved" "$NAME"
-    exit 0
+	notify-send -i "$ICON_DIR/video.png" -u normal "Video Saved" "$NAME"
+	exit 0
 else
-    notify_and_exit
+	notify_and_exit
 fi
diff --git a/scripts/screenshot b/scripts/screenshot
--- a/scripts/screenshot
+++ b/scripts/screenshot
@@ -6,13 +6,13 @@ FULL_FILE=$(date +'%Y%e%d-%s.png')
 SHORT_FILE=$(date +'%s.png')
 
 notify_and_exit () {
-    notify-send -i "$ICON_DIR/error.png" -u normal "Screenshot Failed" "Unable to save screenshot"
-    exit 1
+	notify-send -i "$ICON_DIR/error.png" -u normal "Screenshot Failed" "Unable to save screenshot"
+	exit 1
 }
 
 if [ "$1" = "--edit" ] || [ "$1" = "-e" ]; then
-    grim -g "$(slurp)" - | swappy -f -
-    exit 0
+	grim -g "$(slurp)" - | swappy -f -
+	exit 0
 fi
 
 mkdir -p "$DIR"
@@ -26,8 +26,8 @@ mv "$TEMP_FILE" "$DIR/$NAME" || notify_and_exit
 wl-copy < "$DIR/$NAME"
 
 if [ -s "$DIR/$NAME" ]; then
-    notify-send -i "$DIR/$NAME" -u normal "Screenshot Saved" "$NAME"
-    exit 0
+	notify-send -i "$DIR/$NAME" -u normal "Screenshot Saved" "$NAME"
+	exit 0
 else
-    notify_and_exit
+	notify_and_exit
 fi
